import type { AppContextValue } from "@/context/AppContext";

export type AppContextValueForAi = Pick<
  AppContextValue,
  | "currentUser"
  | "users"
  | "connections"
  | "posts"
  | "visibleFeedPosts"
  | "groups"
  | "groupMessages"
  | "notifications"
  | "settings"
  | "visibleGroups"
  | "searchUsers"
  | "sendRequest"
  | "respondRequest"
  | "deleteConnection"
  | "getAcceptedConnectionIds"
  | "getConnectionStatus"
  | "createGroup"
  | "updateGroupName"
  | "addGroupMembers"
  | "removeGroupMember"
  | "exitGroup"
  | "addPost"
  | "updatePost"
  | "deletePost"
  | "togglePostLike"
  | "addPostComment"
  | "updatePostComment"
  | "deletePostComment"
  | "addGroupMessage"
  | "updateGroupMessage"
  | "deleteGroupMessage"
  | "clearGroupChat"
  | "toggleGroupMessagePin"
  | "toggleGroupMessageReaction"
  | "markGroupMessagesRead"
  | "markGroupNotificationsRead"
  | "markNotificationsForLinkRead"
  | "toggleMuteGroup"
  | "isGroupMuted"
  | "updateTheme"
  | "updateUserSettings"
  | "updateTimeFormat"
  | "runRetentionCleanup"
  | "markNotificationsRead"
>;
